<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <NoWarn>CS1591;CS0649;NU1608;NU1109;SC023</NoWarn>
    <Version>6.0.2</Version>
    <LangVersion>preview</LangVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <PackageTags>Pandoc, Document, Conversion</PackageTags>
    <Description>Conversion of document via Pandoc.</Description>
    <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <PackageLicenseFile>OsmfEula.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Verify_SponsorshipLicenseIgnored>true</Verify_SponsorshipLicenseIgnored>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\OsmfEula.txt" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>
</Project>
